### ISSUE TITLE
Unable to locate message source for category 'modules/fm/module'

### ISSUE THREAD

**Issue by polinwei** [Dominus77/fm#1]
I following your README.md . Workable in web site, but got error while `running php yii `

```
Y:\xampp\htdocs\myweb>php yii
Exception 'yii\base\InvalidConfigException' with message 'Unable to locate message source for category 'modules/fm/module'.'

in Y:\xampp\htdocs\myweb\vendor\yiisoft\yii2\i18n\I18N.php:200

in Y:\xampp\htdocs\myweb\vendor\yiisoft\yii2\i18n\I18N.php:200

Stack trace:
#0 Y:\xampp\htdocs\myweb\vendor\yiisoft\yii2\i18n\I18N.php(88): yii\i18n\I18N->getMessageSource('modules/fm/modu...')
#1 Y:\xampp\htdocs\myweb\vendor\yiisoft\yii2\BaseYii.php(509): yii\i18n\I18N->translate('modules/fm/modu...', 'uploads', Array, 'en')
#2 Y:\xampp\htdocs\myweb\modules\fm\Module.php(85): yii\BaseYii::t('modules/fm/modu...', 'uploads', Array, NULL)
#3 Y:\xampp\htdocs\myweb\modules\fm\Module.php(67): modules\fm\Module::t('module', 'uploads')
#4 Y:\xampp\htdocs\myweb\vendor\yiisoft\yii2\base\Object.php(107): modules\fm\Module->init()

```

**Comment by Dominus77** [comment]
Hi! 
Add your in console config Bootstrap.php for module fm

**Comment by Dominus77** [comment]
here: [https://github.com/Dominus77/yii2-advanced-start/blob/3ecb9bc88e546392847a989467aeb625d0f092fc/console/config/main.php#L17](https://github.com/Dominus77/yii2-advanced-start/blob/3ecb9bc88e546392847a989467aeb625d0f092fc/console/config/main.php#L17)
The console application can not find the configuration of i18n for the module fm

**Comment by Dominus77** [comment]
Updated on README.md

**Comment by polinwei** [comment]
Got it . Thanks
